### ISSUE TITLE
How do i enable the feature that says what block im looking at?

### ISSUE THREAD

**Issue by Kartulit** [Hamster-Systems/Hamster-Systems-Suggestions#2]
All my friends have the feature but for me its missing. How do i enable it?

**Comment by CharleyJQ** [comment]
This is a mod called "The One Probe" this is enabled by default normally. If not on join you should have an item called "The One Probe Read Me" 
![image](https://github.com/Hamster-Systems/Hamster-Systems-Suggestions/assets/38535135/f9b42066-2009-413a-9194-8e389f50c366)

You can make it with 2 redstone and a paper (Shown below)
![image](https://github.com/Hamster-Systems/Hamster-Systems-Suggestions/assets/38535135/6796895c-2d46-4236-ac90-753935698cec)

When you right click it you will get the below menu. 
![image](https://github.com/Hamster-Systems/Hamster-Systems-Suggestions/assets/38535135/ea2c66bb-c0ca-41cf-b7cb-09ba55731d50)

Most use the "Extended" mode where you can right click + shift to change its movement etc.

**Comment by CharleyJQ** [comment]
Hopfully this helps you :) If you need any other help please create a new issue. Many Thanks.
